version: '3.8'

services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
      - my_name=router1
      - my_ip=172.18.1.2
      - router_links=router4,router3,router2
      - router4_ip=172.18.4.2
      - router3_ip=172.18.3.2
      - router2_ip=172.18.2.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.2
      subnet_2:
        ipv4_address: 172.18.2.3
      subnet_3:
        ipv4_address: 172.18.3.3
      subnet_4:
        ipv4_address: 172.18.4.3
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/app/logs

  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
      - my_name=router2
      - my_ip=172.18.2.2
      - router_links=router1,router3
      - router1_ip=172.18.1.2
      - router3_ip=172.18.3.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.3
      subnet_2:
        ipv4_address: 172.18.2.2
      subnet_3:
        ipv4_address: 172.18.3.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/app/logs

  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
      - my_name=router3
      - my_ip=172.18.3.2
      - router_links=router1,router4,router2
      - router1_ip=172.18.1.2
      - router4_ip=172.18.4.2
      - router2_ip=172.18.2.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.4
      subnet_2:
        ipv4_address: 172.18.2.4
      subnet_3:
        ipv4_address: 172.18.3.2
      subnet_4:
        ipv4_address: 172.18.4.4
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/app/logs

  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
      - my_name=router4
      - my_ip=172.18.4.2
      - router_links=router1,router5,router3
      - router1_ip=172.18.1.2
      - router5_ip=172.18.5.2
      - router3_ip=172.18.3.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.5
      subnet_3:
        ipv4_address: 172.18.3.5
      subnet_4:
        ipv4_address: 172.18.4.2
      subnet_5:
        ipv4_address: 172.18.5.3
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/app/logs

  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
      - my_name=router5
      - my_ip=172.18.5.2
      - router_links=router4
      - router4_ip=172.18.4.2
    networks:
      subnet_4:
        ipv4_address: 172.18.4.5
      subnet_5:
        ipv4_address: 172.18.5.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./logs:/app/logs

  host1a:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host1a
      - my_ip=172.18.1.10
      - gateway_ip=172.18.1.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.10
    depends_on:
      - router1
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host1b:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host1b
      - my_ip=172.18.1.11
      - gateway_ip=172.18.1.2
    networks:
      subnet_1:
        ipv4_address: 172.18.1.11
    depends_on:
      - router1
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host2a:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host2a
      - my_ip=172.18.2.10
      - gateway_ip=172.18.2.2
    networks:
      subnet_2:
        ipv4_address: 172.18.2.10
    depends_on:
      - router2
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host2b:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host2b
      - my_ip=172.18.2.11
      - gateway_ip=172.18.2.2
    networks:
      subnet_2:
        ipv4_address: 172.18.2.11
    depends_on:
      - router2
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host3a:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host3a
      - my_ip=172.18.3.10
      - gateway_ip=172.18.3.2
    networks:
      subnet_3:
        ipv4_address: 172.18.3.10
    depends_on:
      - router3
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host3b:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host3b
      - my_ip=172.18.3.11
      - gateway_ip=172.18.3.2
    networks:
      subnet_3:
        ipv4_address: 172.18.3.11
    depends_on:
      - router3
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host4a:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host4a
      - my_ip=172.18.4.10
      - gateway_ip=172.18.4.2
    networks:
      subnet_4:
        ipv4_address: 172.18.4.10
    depends_on:
      - router4
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host4b:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host4b
      - my_ip=172.18.4.11
      - gateway_ip=172.18.4.2
    networks:
      subnet_4:
        ipv4_address: 172.18.4.11
    depends_on:
      - router4
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.5.10' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host5a:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host5a
      - my_ip=172.18.5.10
      - gateway_ip=172.18.5.2
    networks:
      subnet_5:
        ipv4_address: 172.18.5.10
    depends_on:
      - router5
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.11' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

  host5b:
    build:
      context: ./host
      dockerfile: Dockerfile
    environment:
      - my_name=host5b
      - my_ip=172.18.5.11
      - gateway_ip=172.18.5.2
    networks:
      subnet_5:
        ipv4_address: 172.18.5.11
    depends_on:
      - router5
    command: ["sh", "-c", "sleep 10 && python host.py --test 'ping 172.18.1.10' 'ping 172.18.1.11' 'ping 172.18.2.10' 'ping 172.18.2.11' 'ping 172.18.3.10' 'ping 172.18.3.11' 'ping 172.18.4.10' 'ping 172.18.4.11' 'ping 172.18.5.10' 'ping 172.18.1.2' 'ping 172.18.2.2' 'ping 172.18.3.2' 'ping 172.18.4.2' 'ping 172.18.5.2'"]
    volumes:
      - ./logs:/app/logs
    cap_add:
      - NET_ADMIN

networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.3.0/24
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.4.0/24
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.18.5.0/24
